version: "3.8"

services:
  stablediffusion4r_api-storybook:
    image: stablediffusion4r-storybook
    container_name: stablediffusion4r-storybook
    build:
      context: ./frontend/
      dockerfile: ./storybook.Dockerfile
    ports:
      - 6006:6006
    tty: true
  stablediffusion4r_api-frontend:
    image: stablediffusion4r_api-frontend
    container_name: stablediffusion4r_api-frontend
    build:
      context: ./frontend/
      dockerfile: ./frontend.Dockerfile
    ports:
      - 3000:3000
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    tty: true
    depends_on:
      - stablediffusion4r_api-backend
  stablediffusion4r_api-backend:
    image: stablediffusion4r_api-backend
    container_name: stablediffusion4r_api-backend
    build:
      context: ./backend/developmentApi
      dockerfile: ./backend.Dockerfile
    ports:
      - 8787:8787
    tty: true
